---

- name: (AlmaLinux/Amazon Linux/CentOS/Oracle Linux/RHEL/Rocky Linux) "{{ nginx_setup | capitalize }}" NGINX
  ansible.builtin.yum:
    name: nginx{{ nginx_version | default('') }}
    state: "{{ nginx_state }}"
    update_cache: true
    allow_downgrade: "{{ omit if ansible_version['full'] is version('2.12', '<') else true }}"
  ignore_errors: "{{ ansible_check_mode }}"
  notify: (Handler) Run NGINX



- name: Register NGINX config
  ansible.builtin.command: nginx -T
  ignore_errors: "{{ ansible_check_mode }}"
  check_mode: false
  changed_when: false
  register: config_full



- name: (Amazon Linux/CentOS/Oracle Linux/RHEL) Install logrotate
  ansible.builtin.yum:
    name: logrotate
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Create logrotate config
  ansible.builtin.template:
    src: nginx.j2
    dest: /etc/logrotate.d/nginx
    mode: "0644"
  notify: (Handler) Run logrotate


- name: permit traffic in default zone for http service
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled

- name: permit traffic in default zone for https service
  ansible.posix.firewalld:
    service: https
    permanent: true
    state: enabled

- name: reload service firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

