---
# vars file for deploy_nginx

nginx_setup_vars: [install, uninstall, upgrade]
nginx_install_from_vars: [nginx_repository, source, os_repository]
nginx_branch_vars: [mainline, stable]
nginx_state_vals:
  install: present
  uninstall: absent
  upgrade: latest
nginx_default_setup: install
nginx_state: "{{ nginx_state_vals[nginx_setup] | default(nginx_state_vals[nginx_default_setup]) }}"
nginx_modules_list: [geoip, image-filter, njs, perl, xslt]
nginx_plus_modules_list: [auth-spnego, brotli, encrypted-session, geoip, geoip2, headers-more, image-filter, lua, ndk, njs, opentracing, passenger, perl, prometheus, rtmp, set-misc, subs-filter, xslt]

